# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15db73e574e4a51f9ea6a731724ae4c39dcb12faa6c5fb8305b57cfb5ee31c9d31e5a30960949d6b38b14ab6a87ebd18f0913977c1420dbfdfd40bed730aef1d

test:
  secret_key_base: c4c9d26bd000710de1c38adda59b3fa5eb0fe5c9ad7431930b95ef3d7c00b8375aa4671f43737b61bf707beed02c622a593e1c40f59d273b93df836428fbeb42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
